version: "3.9"
services:
  web:
    build: web
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - avatar-images:/var/www/avatar
  frontend:
    build: frontend
    command: npm run dev
    environment:
      PORT: ${FRONTEND_PORT}
      API_URL: http://backend:${BACKEND_PORT}/api
      NEXT_PUBLIC_API_URL: ${PUBLIC_API_URL}
      NEXT_PUBLIC_WEB_URL: ${PUBLIC_WEB_URL}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      JWT_SECRET: ${FRONTEND_JWT_SECRET}
      OAUTH_42_CLIENT_ID: ${OAUTH_42_CLIENT_ID}
      OAUTH_REDIRECT_URI: ${OAUTH_REDIRECT_URI}
    depends_on:
      backend:
        condition: service_healthy
      db:
        condition: service_healthy
  backend:
    build: backend
    command: sh -c "yarn start:dev"
    environment:
      PORT: ${BACKEND_PORT}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      TWO_FACTOR_AUTHENTICATION_APP_NAME: ${TWO_FACTOR_AUTHENTICATION_APP_NAME}
      OAUTH_42_CLIENT_ID: ${OAUTH_42_CLIENT_ID}
      OAUTH_42_CLIENT_SECRET: ${OAUTH_42_CLIENT_SECRET}
      OAUTH_REDIRECT_URI: ${OAUTH_REDIRECT_URI}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT}/api"]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - avatar-images:/app/public/avatar
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  avatar-images:
