services:
  web:
    volumes:
      - ./web/html:/var/www/playground
  frontend:
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
  backend:
    volumes:
      - ./backend:/app
      - backend-node-modules:/app/node_modules

volumes:
  frontend-node-modules:
  backend-node-modules:
