services:
  web:
    volumes:
      - ./web/html:/var/www/playground
      - ./web/nginx.conf:/etc/nginx/nginx.conf
  backend:
    command: sh -c "yarn install && yarn build && yarn prisma migrate deploy && yarn start:dev"
    volumes:
      - ./backend:/app
  frontend:
    volumes:
      - ./frontend:/app
