version: "3.9"
services:
  web:
    build: web
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
  frontend:
    build: frontend
    command: npm run dev
    environment:
      PORT: ${FRONTEND_PORT}
      API_URL: http://backend:${BACKEND_PORT}/api
      NEXT_PUBLIC_API_URL: ${HOST_URL}:${NGINX_PORT}/api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${FRONTEND_PORT}/"]
      interval: 10s
      timeout: 5s
      retries: 30
    depends_on:
      backend:
        condition: service_healthy
      db:
        condition: service_healthy
  backend:
    build: backend
    command: sh -c "yarn prisma migrate deploy && yarn start:dev"
    environment:
      PORT: ${BACKEND_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT}/api"]
      interval: 1s
      timeout: 5s
      retries: 30
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 30
