version: "3.9"
services:
  web:
    build: web
    ports:
      - "4242:80"
    depends_on:
      - backend
      - frontend
  frontend:
    build: frontend
    command: sh -c "npm run build && npm run start"
    depends_on:
      backend:
        condition: service_started
      db:
        condition: service_healthy
  backend:
    build: backend
    command: sh -c "yarn prisma migrate dev && yarn start"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 30
