version: '3.9'
services:
  web:
    image: nginx:alpine
    ports:
      - "4242:80"
    volumes:
      - ./web/html:/var/www/html
      - ./web/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
  backend:
    build: backend
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    command: yarn start
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  backend_node_modules:
