version: '3.9'
services:
  web:
    image: nginx:alpine
    ports:
      - "4242:80"
    volumes:
      - ./web/html:/var/www/html
      - ./web/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
  backend:
    build: backend
    volumes:
      - ./backend:/home/backend/api
      - backend_node_modules:/home/backend/api/node_modules

volumes:
  backend_node_modules:
