services:
  frontend:
    command: sh -c "npm run build && npm run start"
  backend:
    command: sh -c "yarn prisma migrate deploy && yarn start"
    healthcheck:
      interval: 1m
  db:
    healthcheck:
      interval: 1m
