name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ssh_key
          chmod 600 ssh_key
          ssh -oStrictHostKeyChecking=no -i ssh_key ubuntu@ec2-35-78-76-108.ap-northeast-1.compute.amazonaws.com "cd /home/ubuntu/pong && git fetch --all && git checkout ${{ github.sha }} && make prod"
