name: Test the application
on: [pull_request]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate .env file
        run: |
          touch .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env

      - name: Build images
        run: docker compose build

      - name: Run backend unit tests
        run: docker compose run backend sh -c "yarn test"

      - name: Run backend e2e tests
        run: docker compose run backend sh -c "yarn test:e2e"
